import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Check, Clock3, FileCheck2, Mail, MapPin, MonitorSmartphone, Phone, Quote, TrainFront } from "lucide-react";
import { Checkout, ContactForm, SignatureFlow } from "./Interactive";
import { alternateFor, contact, hrefFor, pages, privacySections, services, ui, type Lang } from "@/lib/site";

const icons = { desk: Building2, building: BadgeCheck, mail: Mail, monitor: MonitorSmartphone };
export function PageView({ pageKey, lang }: { pageKey: string; lang: Lang }) {
  const page = pages[pageKey]; const t = ui[lang]; const it = lang === "it"; const home = lang === "it" ? "/" : "/en/index.html";
  return <main id="main">
    {page.kind === "home" ? <>
      <section className="hero home-hero">
        <Image src="/images/office-hero.jpg" alt={it ? "Ufficio arredato moderno e luminoso" : "Bright modern furnished office"} fill priority sizes="100vw" />
        <div className="hero-shade" /><div className="hero-content shell"><span className="eyebrow light">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.description}</p><div className="hero-actions"><Link href={it ? "/tariffe.html" : "/en/pricing.html"} className="button accent">{t.activate}<ArrowRight /></Link><a href={`tel:${contact.phoneHref}`} className="call-link"><Phone />{t.call}</a></div></div>
        <div className="hero-facts shell"><div><b>2014</b><span>{it ? "al fianco delle imprese" : "supporting businesses"}</span></div><div><b>Roma</b><span>{it ? "centro, a due passi da Termini" : "centre, steps from Termini"}</span></div><div><b>8:30–18:00</b><span>{it ? "reception dedicata" : "dedicated reception"}</span></div></div>
      </section>
      <section className="section shell"><div className="section-heading"><div><span className="eyebrow">{it ? "SOLUZIONI" : "SOLUTIONS"}</span><h2>{it ? "Tutto ciò che serve al tuo business" : "Everything your business needs"}</h2></div><p>{it ? "Spazi, indirizzo e servizi professionali in un unico luogo, con la flessibilità di scegliere solo ciò che serve." : "Workspace, business address and professional services in one place—with the flexibility to choose only what you need."}</p></div><ServiceGrid lang={lang} /></section>
      <section className="split-section"><div className="split-image"><Image src="/images/office-hero.jpg" alt="" fill sizes="50vw" /></div><div className="split-copy"><span className="eyebrow">PALAZZO GENTILONI</span><h2>{it ? "Il prestigio della storia, l’efficienza del presente" : "Historic prestige, modern efficiency"}</h2><p>{it ? "Al primo piano di Palazzo Gentiloni, ambienti curati e tecnologie all’avanguardia accolgono il tuo lavoro e i tuoi clienti." : "On the first floor of Palazzo Gentiloni, refined spaces and up-to-date technology welcome you, your work and your clients."}</p><ul className="check-list"><li><Check />{it ? "Posizione centrale e rappresentativa" : "Central, prestigious location"}</li><li><Check />{it ? "Spazi pronti e connessi" : "Connected, ready-to-use spaces"}</li><li><Check />{it ? "Assistenza professionale" : "Professional support"}</li></ul><Link className="arrow-link" href={it ? "/chi-siamo.html" : "/en/about.html"}>{it ? "CONOSCI ROMA OFFICE SHARING" : "MEET ROMA OFFICE SHARING"}<ArrowRight /></Link></div></section>
      <Cta lang={lang} />
    </> : <>
      <section className="page-hero"><div className="shell"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.description}</p></div></section>
      <Breadcrumb lang={lang} title={page.title} home={home} />
      <PageBody kind={page.kind} lang={lang} pageKey={pageKey} />
    </>}
  </main>;
}

function Breadcrumb({ lang, title, home }: {lang:Lang;title:string;home:string}) { return <nav className="breadcrumb shell" aria-label="Breadcrumb"><Link href={home}>{ui[lang].home}</Link><span>/</span><span aria-current="page">{title}</span></nav>; }
function ServiceGrid({lang}:{lang:Lang}) { return <div className="service-grid">{services[lang].map(s=>{const Icon=icons[s.icon as keyof typeof icons];return <article className="service-card" key={s.title}><div className="service-icon"><Icon /></div><h3>{s.title}</h3><p>{s.text}</p><Link href={s.href}>{ui[lang].discover}<ArrowRight/><span className="sr-only">: {s.title}</span></Link></article>})}</div>; }
function Cta({lang}:{lang:Lang}) {const it=lang==="it";return <section className="cta-band"><div className="shell"><div><span className="eyebrow light">{it?"PARLIAMONE":"LET’S TALK"}</span><h2>{it?"Pronto a dare spazio alla tua attività?":"Ready to give your business room to grow?"}</h2></div><div><Link className="button accent" href={it?"/contatti.html":"/en/contact.html"}>{it?"RICHIEDI INFORMAZIONI":"REQUEST INFORMATION"}<ArrowRight/></Link><a href={`tel:${contact.phoneHref}`}>{ui[lang].call}</a></div></div></section>}

function PageBody({kind,lang,pageKey}:{kind:string;lang:Lang;pageKey:string}) {
 const it=lang==="it"; const p=pages[pageKey]; const t=ui[lang];
 if(kind==="contact") return <section className="section shell contact-layout"><div><span className="eyebrow">{it?"SCRIVICI":"WRITE TO US"}</span><h2>{it?"Come possiamo aiutarti?":"How can we help?"}</h2><ContactForm lang={lang}/></div><aside className="contact-aside"><div className="contact-detail"><MapPin/><div><b>{it?"Indirizzo":"Address"}</b><p>{contact.address}</p></div></div><div className="contact-detail"><Phone/><div><b>{it?"Telefono":"Phone"}</b><p><a href={`tel:${contact.phoneHref}`}>{contact.phone}</a><br/>Fax {contact.fax}</p></div></div><div className="contact-detail"><Mail/><div><b>Email</b><p><a href={`mailto:${contact.email}`}>{contact.email}</a></p></div></div><div className="contact-detail"><Clock3/><div><b>{ui[lang].hours}</b><p>{ui[lang].weekdays}<br/>{ui[lang].saturday}</p></div></div><Map lang={lang}/></aside></section>;
 if(kind==="pricing") return <><section className="section shell"><div className="section-heading"><div><span className="eyebrow">{it?"ACQUISTA ONLINE":"BUY ONLINE"}</span><h2>{it?"Configura la domiciliazione":"Configure domiciliation"}</h2></div><p>{it?"Scegli servizio e durata. Vedrai sempre imponibile, IVA e totale prima di procedere al pagamento sicuro.":"Choose the service and duration. You will always see the base fee, VAT and total before secure payment."}</p></div><div className="pricing-layout"><Checkout lang={lang}/><div className="process-card"><span className="step-label">02 — {it?"DOPO IL PAGAMENTO":"AFTER PAYMENT"}</span><h3>{it?"Verifica e firma online":"Verify and sign online"}</h3><ol><li><span>1</span>{it?"Compila la richiesta di domiciliazione":"Complete the domiciliation application"}</li><li><span>2</span>{it?"Verifica il cellulare tramite SMS OTP":"Verify your mobile by SMS OTP"}</li><li><span>3</span>{it?"Firma e ricevi il PDF tramite link sicuro":"Sign and receive the PDF through a secure link"}</li></ol><SignatureFlow lang={lang}/></div></div></section><Cta lang={lang}/></>;
 if(kind==="legal") return <><section className="section shell narrow"><div className="editorial"><span className="eyebrow">{it?"COSA INCLUDE":"WHAT’S INCLUDED"}</span><h2>{it?"Una sede legale affidabile e rappresentativa":"A credible, prestigious registered office"}</h2><p>{it?"Il servizio consente di eleggere la sede legale della società presso il nostro indirizzo, con ricezione e gestione della corrispondenza secondo le modalità concordate.":"The service allows your company to establish its registered office at our address, with receipt and handling of correspondence under the agreed arrangements."}</p><div className="feature-columns"><Feature title={it?"Vantaggi":"Benefits"} items={it?["Indirizzo prestigioso nel centro di Roma","Separazione tra sede e abitazione","Reception e notifiche della posta"]:["Prestigious central Rome address","Separation of home and registered office","Reception and mail notifications"]}/><Feature title={it?"Documenti richiesti":"Required documents"} items={it?["Documento e codice fiscale del legale rappresentante","Visura o atto costitutivo","Modulo antiriciclaggio e delega"]:["Director’s ID and tax code","Company extract or incorporation deed","AML form and authorisation"]}/></div><h2>{it?"Procedura semplice":"A straightforward process"}</h2><div className="timeline"><div><span>01</span><h3>{it?"Contratto":"Agreement"}</h3><p>{it?"Scegli durata e servizi, completa i dati e sottoscrivi il contratto.":"Choose duration and services, enter your details and sign the agreement."}</p></div><div><span>02</span><h3>{it?"Attivazione":"Activation"}</h3><p>{it?"Dopo verifica dei documenti ricevi la conferma di attivazione.":"After document checks, you receive activation confirmation."}</p></div><div><span>03</span><h3>{it?"Ritiro posta":"Mail collection"}</h3><p>{it?"Ti avvisiamo della corrispondenza, disponibile per ritiro o inoltro.":"We notify you of mail, available for collection or forwarding."}</p></div></div><Link className="button primary" href={it?"/tariffe.html":"/en/pricing.html"}>{it?"VEDI TARIFFE E ATTIVA":"SEE PRICING & ACTIVATE"}<ArrowRight/></Link></div></section><Cta lang={lang}/></>;
 if(kind==="privacy") return <section className="section shell legal-text"><div className="notice"><FileCheck2/><p>{it?"Il testo italiano della presente informativa è la versione autorevole.":"This is a faithful English translation. In case of discrepancy, the Italian original is authoritative."}</p></div><h2>{it?"INFORMATIVA PRIVACY":"PRIVACY NOTICE"}</h2>{privacySections[lang].map(([h,b])=><section key={h}><h3>{h}</h3><p>{b}</p></section>)}<p><b>{ui[lang].revoke}</b></p></section>;
 if(kind==="cookies") return <section className="section shell legal-text"><h2>{it?"Cosa sono i cookie":"What cookies are"}</h2><p>{it?"I cookie sono piccoli file memorizzati dal browser. Questo sito usa cookie tecnici necessari e, con consenso, categorie analitiche e di marketing.":"Cookies are small files stored by your browser. This site uses necessary technical cookies and, with consent, analytics and marketing categories."}</p><h3>{it?"Categorie e durata":"Categories and duration"}</h3><div className="table-wrap"><table><thead><tr><th>{it?"Categoria":"Category"}</th><th>{it?"Finalità":"Purpose"}</th><th>{it?"Durata":"Duration"}</th></tr></thead><tbody><tr><td>{it?"Necessari":"Necessary"}</td><td>{it?"Preferenze consenso e sicurezza":"Consent preferences and security"}</td><td>6 {it?"mesi":"months"}</td></tr><tr><td>{it?"Analitici":"Analytics"}</td><td>{it?"Statistiche aggregate, solo previo consenso":"Aggregate metrics, only with consent"}</td><td>13 {it?"mesi":"months"}</td></tr><tr><td>Marketing</td><td>{it?"Contenuti e campagne, solo previo consenso":"Content and campaigns, only with consent"}</td><td>6 {it?"mesi":"months"}</td></tr></tbody></table></div><h3>{it?"Gestire o revocare il consenso":"Manage or withdraw consent"}</h3><p>{it?"Usa il pulsante seguente in qualsiasi momento. Puoi anche eliminare i cookie dal browser.":"Use the button below at any time. You can also erase cookies in your browser."}</p><button className="button primary" data-cookie-settings>{ui[lang].settings}</button><p>{ui[lang].revoke}</p></section>;
 if(kind==="location") return <><section className="map-full"><Map lang={lang}/></section><section className="section shell location-grid"><div><span className="eyebrow">{it?"INDIRIZZO":"ADDRESS"}</span><h2>{contact.address}</h2><p>{it?"Siamo al primo piano di Palazzo Gentiloni, in una delle zone più centrali e ben collegate di Roma.":"We are on the first floor of Palazzo Gentiloni, in one of Rome’s most central and well-connected districts."}</p></div><div className="travel-list"><div><TrainFront/><p><b>Roma Termini</b><br/>{it?"Circa 10 minuti a piedi o poche fermate in autobus.":"Around a 10-minute walk or a short bus ride."}</p></div><div><MapPin/><p><b>Fiumicino & Ciampino</b><br/>{it?"Collegamenti ferroviari e bus diretti per Termini.":"Direct rail and coach services to Termini."}</p></div></div></section><Cta lang={lang}/></>;
 if(kind==="about") return <><section className="section shell narrative"><span className="eyebrow">{it?"DAL 2014":"SINCE 2014"}</span><h2>{it?"Siamo parte della crescita dei nostri clienti dal 2014":"We have been part of our clients’ growth since 2014"}</h2><p className="lead">{it?"Roma Office Sharing nasce dall’esperienza di Cube Engineering s.r.l. per offrire ad aziende e professionisti spazi e servizi affidabili, flessibili e curati.":"Roma Office Sharing was created from Cube Engineering s.r.l.’s experience to give businesses and professionals dependable, flexible and carefully managed spaces and services."}</p><div className="values"><div><b>01</b><h3>{it?"Missione":"Mission"}</h3><p>{it?"Liberare imprese e professionisti dagli oneri di gestione, perché possano concentrarsi sulla crescita.":"Free businesses and professionals from office overhead so they can focus on growth."}</p></div><div><b>02</b><h3>{it?"Accoglienza":"Hospitality"}</h3><p>{it?"Creare un’esperienza professionale e autenticamente romana per ogni cliente e ospite.":"Create a professional and authentically Roman experience for every client and guest."}</p></div><div><b>03</b><h3>{it?"Affidabilità":"Reliability"}</h3><p>{it?"Un rapporto trasparente, servizi puntuali e attenzione ai dettagli.":"Transparent relationships, timely services and close attention to detail."}</p></div></div></section><Cta lang={lang}/></>;
 if(kind==="testimonials") return <><section className="section shell"><div className="testimonial-grid">{[it?"Un punto di riferimento professionale e sempre disponibile.":"A professional, consistently responsive point of reference.",it?"Spazi curati e posizione davvero comoda per incontrare i clienti.":"Well-designed spaces in a genuinely convenient location for client meetings.",it?"La domiciliazione è gestita con precisione e cortesia.":"Domiciliation is handled accurately and courteously."].map((q,i)=><figure key={q}><Quote/><blockquote>“{q}”</blockquote><figcaption>{it?"Testimonianza segnaposto":"Placeholder testimonial"} {i+1}<small>{it?"Sostituire con recensione verificata":"Replace with a verified review"}</small></figcaption></figure>)}</div></section><Cta lang={lang}/></>;
 return <><section className="section shell service-detail"><div><span className="eyebrow">{it?"IL SERVIZIO":"THE SERVICE"}</span><h2>{p.intro || (it?"Una soluzione professionale, semplice e flessibile":"A professional, simple and flexible solution")}</h2><p>{it?"Costruiamo il servizio intorno alle esigenze della tua attività, con assistenza dedicata e condizioni trasparenti.":"We shape the service around your organisation, with dedicated support and transparent terms."}</p>{p.bullets&&<Feature title={it?"Cosa include":"What’s included"} items={p.bullets}/>}<Link href={it?"/contatti.html":"/en/contact.html"} className="button primary">{t.activate}<ArrowRight/></Link></div><aside className="service-side"><div><b>{it?"Hai bisogno di aiuto?":"Need help?"}</b><p>{it?"Parla con il nostro team per configurare la soluzione giusta.":"Speak to our team to configure the right solution."}</p><a href={`tel:${contact.phoneHref}`} className="arrow-link"><Phone/>{t.call}</a></div></aside></section><Cta lang={lang}/></>;
}
function Feature({title,items}:{title:string;items:string[]}){return <div><h3>{title}</h3><ul className="check-list">{items.map(i=><li key={i}><Check/>{i}</li>)}</ul></div>}
function Map({lang}:{lang:Lang}){return <iframe className="map" title={lang==="it"?"Mappa di Via Venti Settembre 118, Roma":"Map of Via Venti Settembre 118, Rome"} loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=12.4935%2C41.9018%2C12.5005%2C41.9072&layer=mapnik&marker=41.9045%2C12.4970"/>}
